services:
  vite:
    command: ["npm", "run", "build"]
    environment:
      NODE_ENV: "production"
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - type: bind
        source: ${COMSES_APP_ROOT:-.}/deploy/nginx/nginx-haproxy.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_APP_ROOT:-.}/deploy/nginx/uwsgi_params
        target: /etc/nginx/uwsgi_params
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_SHARED_ROOT:-./docker/shared}/tls/well-known
        target: /srv/.well-known
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_LOG_ROOT:-./docker/shared/logs}/nginx
        target: /var/log/nginx
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_SHARED_ROOT:-./docker/shared}/static
        target: /srv/static
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_SHARED_ROOT:-./docker/shared}/media
        target: /srv/media
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_SHARED_ROOT:-./docker/shared}/library
        target: /library
        read_only: true
        bind:
          create_host_path: false
      - sockets:/shared/sockets
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "80:80"
  server:
    build:
      context: ./django
      args:
        REQUIREMENTS_FILE: requirements.txt
        UBUNTU_MIRROR: "mirror.it.ubc.ca"
        RUN_SCRIPT: "./deploy/prod.sh"
    image: comses/server:${RELEASE_VERSION}
    restart: always
    volumes:
      - type: bind
        source: ${COMSES_SHARED_ROOT:-./docker/shared}
        target: /shared
        bind:
          create_host_path: false
      - type: bind
        source: ${COMSES_LOG_ROOT:-./docker/shared/logs}
        target: /shared/logs
        bind:
          create_host_path: false
      - sockets:/shared/sockets
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.production"
    ports:
      - "127.0.0.1:9191:9191" # uWSGI stats server
    depends_on:
      vite:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
volumes:
  sockets:
    driver: local
